cpt-list: exit if less than two arguments are given
FossilOrigin-Name: 1f2fe5b6d49f546421cd48e6878632dc860ef7366d7ce7893f89752f11e742d5

diff --git a/src/cpt-list b/src/cpt-list
--- a/src/cpt-list
+++ b/src/cpt-list
@@ -35,6 +35,7 @@ if [ "$PKG" ]; then
         printf %s "$2"
     fi
 elif [ "$VERSIONCHECK" ]; then
+    [ "$#" -ge 2 ] || die "Minimum of 2 arguments required, got: $#"
     pkg_list "$1" | grep -Fq "$1 $2 $3"
 else
     [ "$CURRENT" ] && set -- "${PWD##*/}"
